### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by AnAIExpert** [yadavsidhant/quickllm#1]
Hey I guess the library is unable to fetch some module please check this error below:
![Screenshot 2024-07-31 at 7 13 08 PM](https://github.com/user-attachments/assets/3682cdca-eb5a-4c81-a9a0-404fc6fabcb0)

# Error
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-40f76846cb2c> in <cell line: 1>()
----> 1 from quickllm import QuickLLM
      2 
      3 # Initialize QuickLLM
      4 llm = QuickLLM(model_name="gpt2", input_file="/content/OWASP_DATA_PROCESSED_19FEB_SCRAP.txt", output_dir="/content/output")
      5 

/usr/local/lib/python3.10/dist-packages/quickllm/__init__.py in <module>
      2 from typing import List, Optional
      3 from .models import SUPPORTED_MODELS
----> 4 from .finetune import finetune_model
      5 from .chat import chat_with_model
      6 from .visualize import visualize_model

ModuleNotFoundError: No module named 'quickllm.finetune'

---------------------------------------------------------------------------

**Comment by yadavsidhant** [comment]
It looks like the [__init__.py](https://github.com/yadavsidhant/quickllm/blob/main/quickllm/__init__.py) is unable to import the module [finetune.py](https://github.com/yadavsidhant/quickllm/blob/main/quickllm/finetune.py) file due the missnaming of the module rectified in [commit](https://github.com/yadavsidhant/quickllm/commit/a281d4513fdb565dd79f5817b32e1e8ea4a781e1), I'm looking for the issue and rolling up new update soon...

**Comment by yadavsidhant** [comment]
[New Version](https://pypi.org/project/quickllm/0.1.1/) rolled out fixing the issue please install the library again by ```pip install quickllm==0.1.1```
