### ISSUE TITLE
Facing issue with the named 'validation'

### ISSUE THREAD

**Issue by AnAIExpert** [yadavsidhant/quickllm#2]
![Screenshot 2024-07-31 at 7 13 08 PM](https://github.com/user-attachments/assets/50e6bb1d-4a29-4b20-be92-e9014bc04454)
 
# Error
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-2-40f76846cb2c>](https://localhost:8080/#) in <cell line: 7>()
      5 
      6 # Fine-tune the model
----> 7 llm.finetune(objective="chat", epochs=3, learning_rate=2e-5)
      8 
      9 # Chat with the fine-tuned model

2 frames
[/usr/local/lib/python3.10/dist-packages/datasets/dataset_dict.py](https://localhost:8080/#) in __getitem__(self, k)
     73     def __getitem__(self, k) -> Dataset:
     74         if isinstance(k, (str, NamedSplit)) or len(self) == 0:
---> 75             return super().__getitem__(k)
     76         else:
     77             available_suggested_splits = [

KeyError: 'validation'

**Comment by yadavsidhant** [comment]
Check the new version fixing the issue [PYPI](https://pypi.org/project/quickllm/0.1.3/)
