### ISSUE TITLE
Getting Value Error "Asking to pad but the tokenizer does not have a padding token"

### ISSUE THREAD

**Issue by AnAIExpert** [yadavsidhant/quickllm#3]
![Screenshot 2024-07-31 at 7 13 08 PM](https://github.com/user-attachments/assets/5a9180a0-87d8-40d4-ad9c-84933cac8d0b)
 
# Error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-7-daf555f1eaa5>](https://localhost:8080/#) in <cell line: 7>()
      5 
      6 # Fine-tune the model with custom settings
----> 7 llm.finetune(
      8     objective="specific_chat",
      9     epochs=5,

13 frames
[/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py](https://localhost:8080/#) in _get_padding_truncation_strategies(self, padding, truncation, max_length, pad_to_multiple_of, verbose, **kwargs)
   2847         # Test if we have a padding token
   2848         if padding_strategy != PaddingStrategy.DO_NOT_PAD and (self.pad_token is None or self.pad_token_id < 0):
-> 2849             raise ValueError(
   2850                 "Asking to pad but the tokenizer does not have a padding token. "
   2851                 "Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` "

ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.

**Comment by yadavsidhant** [comment]
Currently looking into the issue the fintuner has got some issues due to adding validation set will roll out new version soon..

**Comment by yadavsidhant** [comment]
Currently you can use the [Version 0.1.5](https://pypi.org/project/quickllm/0.1.5/) by:
```pip install quickllm==0.1.5```
 This version is currently the most stable version of quickllm which is not facing any issue **Kindly use this version only not the newer ones** as they are facing some issues in testing, I will soon update the README.md file describing the new functionalities added...
